### ISSUE TITLE
Error when running `crystal spec`

### ISSUE THREAD

**Issue by marceloboeira** [waterlink/spec2.cr#24]
When running `crystal spec` the following error output is given:

`Assertion failed: ((i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"), function init, file /tmp/llvm20151214-69554-hagc7s/llvm-3.6.2.src/lib/IR/Instructions.cpp, line 281.
fish: 'crystal run spec/spec2_spec.cr' terminated by signal SIGABRT (Abort)`

@waterlink  I'm currently trying to implement #23, can you help me with this?

**Comment by waterlink** [comment]
That looks really weird. This is an error from LLVM back-end. Probably we are looking at some compiler bug.

Can you push your branch on your `spec2.cr` fork, so that I can clone and play around with it?

**Comment by waterlink** [comment]
Or, is it just a formatter that you are implementing on `spec2-ns.cr` ?

**Comment by marceloboeira** [comment]
@waterlink It is on the `spec2.cr` repository only, I've followed the contributing guide by cloning it, then I tried to run `crystal spec`. In this specific order. There is no additional code.

**Comment by waterlink** [comment]
Oh, I see.

**Comment by waterlink** [comment]
Yes. Something seems to be changed strangely. I am getting silent `Program exited because of a segmentation fault` (it actually runs some tests). It worked before `crystal` update by the way.

**Comment by waterlink** [comment]
It fails consistently for `subject(...) {...}` and `subject {...}` forms.

**Comment by waterlink** [comment]
@marceloboeira Currently was unable to understand the reason. Debugging doesn't help either. I will try to narrow down the code to minimum failing example and see if it helps.

**Comment by marceloboeira** [comment]
@waterlink alright, if you need any help let me know.

**Comment by waterlink** [comment]
@marceloboeira I think I have a couple of small examples, that I would report as issues to Crystal lang, because I think inheritance + `with self yield` is broken.

**Comment by waterlink** [comment]
I will put links to them here to keep track.

**Comment by waterlink** [comment]
- [x] manastech/crystal#2171
