### ISSUE TITLE
After hooks should be run for failing tests

### ISSUE THREAD

**Issue by RX14** [waterlink/spec2.cr#32]
I use after hooks to clean up after tests. If one test fails, the after hook fails to run and this causes every test after to fail. This makes it a little hard to figure out which test was the root cause.

I think after hooks should run even when the test fails, using a finally block.

**Comment by waterlink** [comment]
@RX14 Thanks for the idea. You are totally right here. Will merge #33 once green and release a new version.

**Comment by waterlink** [comment]
@RX14 I have released `0.8.0` version with the fix.
