### ISSUE TITLE
Error in be.cr

### ISSUE THREAD

**Issue by justaskz** [waterlink/spec2.cr#41]
I am getting this error, however message is not informative at all :(

```
Error in ./libs/spec2/matchers/be.cr:34: macro 'method_missing' expects 1 argument (call)

      macro method_missing(name, args, block)
            ^~~~~~~~~~~~~~

make: *** [test] Error 1
```

**Comment by mauricioabreu** [comment]
Use the master branch. It is fixed but it was not released it.

**Comment by justaskz** [comment]
It works! Thank you

**Comment by fridgerator** [comment]
when can we expect a release for this? I would like to also release an update for the [google_maps_api](https://github.com/fridgerator/google_maps_api) lib

**Comment by waterlink** [comment]
Hi Nick,

I will release the new version in around 7 hours from now.
Nick Franken notifications@github.com schrieb am Mi., 22. Juni 2016 um
7:30 PM:

**Comment by waterlink** [comment]
@fridgerator Published just now: https://github.com/waterlink/spec2.cr/releases/tag/v0.8.2

**Comment by fridgerator** [comment]
👍
