### ISSUE TITLE
Support for `pending` or `xit`?

### ISSUE THREAD

**Issue by miketheman** [waterlink/spec2.cr#52]
Hi there!
Starting out with this on a new library, and was curious if/how might we go about supporting `pending` or skipping tests that are work-in-progress?

The base `spec` has `pending()` - can that be used in conjunction with spec2? I have yet to include `spec` in my spec_helper.

**Comment by waterlink** [comment]
This will have to be implemented on spec2 side. I'll take a look at it
later today.
